format = """
$directory\
$git_branch\
$git_status\
$fill\
$bun\
$nodejs\
$deno\
$rust\
$golang\
$python\
$lua\
$java\
$kotlin\
$c\
$cpp\
$zig\
$ruby\
$php\
$perl\
$elixir\
$haskell\
$scala\
$swift\
$julia\
$nim\
$ocaml\
$crystal\
$dart\
$elm\
$nix_shell\
$docker_context\
$aws\
$gcloud\
$cmd_duration\
$line_break\
$character"""

[fill]
symbol = " "

[git_branch]
symbol = ""
style = "purple"
format = "[\\($symbol $branch]($style)"

[git_status]
style = "red"
format = "[$ahead_behind$modified$untracked$staged$deleted\\)]($style) "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"
stashed = ""
modified = " +${count}"
untracked = " ?${count}"
staged = " ++${count}"
deleted = " -${count}"
conflicted = "=${count} "
renamed = "»${count} "
up_to_date = ""

[aws]
symbol = "  "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
version_format = "${raw}"
symbol = " "
style = "blue"
format = "[$symbol($version )]($style)"

[cpp]
version_format = "${raw}"
symbol = " "
format = "[$symbol($version )]($style)"

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
version_format = "${raw}"
symbol = " "
style = "green"
format = "[$symbol($version )]($style)"

[directory]
read_only = " 󰌾"
truncation_length = 0
truncate_to_repo = false
style = "blue"
repo_root_style = "bold cyan"
before_repo_root_style = "dimmed blue"
format = "[$path]($style) "
repo_root_format = "[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style) "

[docker_context]
symbol = " "

[elixir]
version_format = "${raw}"
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = "  "


[git_commit]
tag_symbol = '  '

[golang]
version_format = "${raw}"
symbol = " "
style = "cyan"
format = "[$symbol($version )]($style)"

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
version_format = "${raw}"
symbol = " "
style = "red"
format = "[$symbol($version )]($style)"

[julia]
symbol = " "

[kotlin]
version_format = "${raw}"
symbol = " "

[lua]
version_format = "${raw}"
symbol = " "
style = "blue"
format = "[$symbol($version )]($style)"

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
version_format = "${raw}"
symbol = " "
style = "green"
format = "[$symbol($version )]($style)"

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "
style = "208"
format = "[$symbol$version ]($style)"

[perl]
symbol = " "

[php]
version_format = "${raw}"
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[python]
version_format = "${raw}"
symbol = " "
style = "yellow"
format = "[$symbol($version )]($style)"

[rlang]
symbol = "󰟔 "

[ruby]
version_format = "${raw}"
symbol = " "

[rust]
version_format = "${raw}"
symbol = "󱘗 "
style = "red"
format = "[$symbol($version )]($style)"

[scala]
symbol = " "

[swift]
version_format = "${raw}"
symbol = " "

[zig]
version_format = "${raw}"
symbol = " "

[gradle]
symbol = " "
