[env]
TERM = "xterm-256color"

[window.padding]
x = 0
y = 0

[colors.bright]
black = "#625e4c"
blue = "#9d65ff"
cyan = "#58d1eb"
green = "#98e024"
magenta = "#f4005f"
red = "#f4005f"
white = "#f6f6ef"
yellow = "#e0d561"

[colors.normal]
black = "#1a1a1a"
blue = "#9d65ff"
cyan = "#58d1eb"
green = "#98e024"
magenta = "#f4005f"
red = "#f4005f"
white = "#c4c5b5"
yellow = "#fa8419"

[colors.primary]
background = "#1a1a1a"
foreground = "#c4c5b5"

[font]
size = 18

[font.normal]
family = "DejaVuSansM Nerd Font"

[keyboard]
bindings = [
  { key = "A", mods = "Command", chars = "\u0001" },
  { key = "B", mods = "Command", chars = "\u0002" },
  { key = "C", mods = "Command", chars = "\u0003" },
  { key = "C", mods = "Command|Shift", action = "Copy" },
  { key = "D", mods = "Command", chars = "\u0004" },
  { key = "E", mods = "Command", chars = "\u0005" },
  { key = "F", mods = "Command", chars = "\u0006" },
  { key = "G", mods = "Command", chars = "\u0007" },
  { key = "H", mods = "Command", chars = "\b" },
  { key = "I", mods = "Command", chars = "\u0009" },
  { key = "J", mods = "Command", chars = "\u000A" },
  { key = "K", mods = "Command", chars = "\u000B" },
  { key = "L", mods = "Command", chars = "\f" },
  { key = "O", mods = "Command", chars = "\u000F" },
  { key = "P", mods = "Command", chars = "\u0010" },
  { key = "P", mods = "Command|Shift", chars = "\u001b[80;6u" },
  { key = "R", mods = "Command", chars = "\u0012" },
  { key = "S", mods = "Command", chars = "\u0013" },
  { key = "T", mods = "Command", chars = "\u0014" },
  { key = "T", mods = "Command|Shift", action = "CreateNewTab" },
  { key = "U", mods = "Command", chars = "\u0015" },
  { key = "V", mods = "Command", chars = "\u0016" },
  { key = "V", mods = "Command|Shift", action = "Paste" },
  { key = "W", mods = "Command", chars = "\u0017" },
  { key = "X", mods = "Command", chars = "\u0018" },
  { key = "Y", mods = "Command", chars = "\u0019" },
  { key = "Z", mods = "Command", chars = "\u001A" },
  { key = "Z", mods = "Command|Shift", chars = "\u001b[122;6u" },
  { key = "/", mods = "Command", chars = "\u001f" },
  { key = "Up", mods = "Command", chars = "\u001b[1;5A" },
  { key = "Down", mods = "Command", chars = "\u001b[1;5B" },
  { key = "Return", mods = "Shift", chars = "\u001b\r" },
]
